

title: Innovation Technological Insistitue
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: kerrongordon
github_username:  Kerron Gordon

baseurl: "/i.t.i"

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :compressed

# image

logo: '/assets/img/logo.svg'