#menu
menu:
- {name: 'Home', link: '/', }
- {name: 'News', link: '/news', }
- {name: 'Virtual Training', link: '/virtual-training', }
- {name: 'Training Materials', link: '/training-materials', }
- {name: 'Partners', link: '/partners', }
- {name: 'About', link: '/about', }
- {name: 'Contact', link: '/contact', }

#footer mmenu

#Content
content:
- {h3: 'Content', }
- {name: 'About', link: '/about', }
- {name: 'Contact', link: '/contact', }
- {name: 'Partners', link: '/partners', }


#Follow Us
followus:
- {h3: 'Follow Us', }
- {name: 'Facebook', link: '/javascript:void(0)', }
- {name: 'Twitter', link: '/javascript:void(0)', }
- {name: 'YouTube', link: '/javascript:void(0)', }


#Legal
legal:
- {h3: 'Legal', }
- {name: 'Terms and Conditions', link: '/javascript:void(0)', }
- {name: 'Privacy Policy', link: '/javascript:void(0)', }



#icons-list
iconslist:
- {name: 'Test', icon: 'icon-book-open', delay: '.20s',}
- {name: 'Work', icon: 'icon-presentation', delay: '.40s',}
- {name: 'Any Time', icon: 'icon-calendar', delay: '.60s',}
- {name: 'Online', icon: 'icon-tools', delay: '.80s',}
- {name: 'Online', icon: 'icon-piechart', delay: '1.0s',}


# home page grid-items

grideitems:
- {name: 'kerron', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>',
	link: '/about', 
	class: 'grid-item', }
- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 

	class: 'grid-item',}

- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 
	class: 'grid-item',}

- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 
	class: 'grid-item',}

- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 
	class: 'grid-item grid-item-big',}

- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 
	class: 'grid-item',}

- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 
	class: 'grid-item',}

- {name: 'gordon', 
	img: '/assets/img/placeholder_logo_1_dark.png', 
	infor: '<p>Lorem ipsum consectetur dolor sit amet consectetur adipisicing elit.</p>', 
	link: '/about', 
	class: 'grid-item',}



#testimonials
testimonials:
- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero voluptates officiis tempore quae officia! Beatae quia deleniti cum corporis eos perferendis libero reiciendis nemo iusto accusamus, debitis tempora voluptas praesentium.',
	img: 'avatar-1',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-2',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-3',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-4',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-5',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-6',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero voluptates officiis tempore quae officia! Beatae quia deleniti cum corporis eos perferendis libero reiciendis nemo iusto accusamus, debitis tempora voluptas praesentium.',
	img: 'avatar-1',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-2',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-3',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-4',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-5',}

- {name: 'MyName',
	jobtitle: 'Designer, CodyHouse',
	content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
	img: 'avatar-6',}


